# movie_romance_rating_5

In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('./movies_data/movies.csv', sep=',', index_col=0)
print(type(movies))
print(movies.shape)
movies.head()

<class 'pandas.core.frame.DataFrame'>
(9125, 2)

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [3]:
ratings = pd.read_csv('./movies_data/ratings.csv', sep=',', parse_dates=['timestamp'])
print(type(ratings))
print(ratings.shape)
print(ratings.head())

<class 'pandas.core.frame.DataFrame'>
(100004, 4)
   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
movies_rating = ratings[['movieId', 'rating']]

In [5]:
rating = movies_rating.groupby('movieId').mean()

In [6]:
rating.head()

           rating
movieId
1        3.872470
2        3.401869
3        3.161017
4        2.384615
5        3.267857

In [14]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9066 entries, 1 to 163949
Data columns (total 1 columns):
rating    9066 non-null float64
dtypes: float64(1)
memory usage: 461.7 KB

In [12]:
result = pd.concat([movies, rating], axis=1, sort=False)
result.head()

,title,genres,rating
movieId,,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.872470
2,Jumanji (1995),Adventure|Children|Fantasy,3.401869
3,Grumpier Old Men (1995),Comedy|Romance,3.161017
4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.384615
5,Father of the Bride Part II (1995),Comedy,3.267857

In [13]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9125 entries, 1 to 164979
Data columns (total 3 columns):
title     9125 non-null object
genres    9125 non-null object
rating    9066 non-null float64
dtypes: float64(1), object(2)
memory usage: 285.2+ KB

In [23]:
movie_romance_rating_5 = result[(result.genres.str.find("Romance")>=0) & (result.rating == 5.0)]
movie_romance_rating_5

,title,genres,rating
movieId,,,
301,Picture Bride (Bijo photo) (1994),Drama|Romance,5.0
764,Heavy (1995),Drama|Romance,5.0
1455,Hotel de Love (1996),Comedy|Romance,5.0
2837,Bedrooms & Hallways (1998),Comedy|Romance,5.0
3612,The Slipper and the Rose: The Story of Cindere...,Adventure|Children|Fantasy|Musical|Romance,5.0
3909,Woman on Top (2000),Comedy|Romance,5.0
4076,Two Ninas (1999),Comedy|Romance,5.0
4088,"Big Town, The (1987)",Drama|Romance|Thriller,5.0
4140,North Shore (1987),Drama|Romance,5.0
4342,Big Eden (2000),Drama|Romance,5.0
4428,"Misfits, The (1961)",Comedy|Drama|Romance|Western,5.0
4522,Masquerade (1988),Mystery|Romance|Thriller,5.0
4584,Dream a Little Dream (1989),Comedy|Drama|Romance,5.0
4626,Miracle Mile (1989),Drama|Romance|Sci-Fi,5.0
4796,"Grass Is Greener, The (1960)",Comedy|Romance,5.0
5071,Maelström (2000),Drama|Romance,5.0
6163,He Loves Me... He Loves Me Not (À la folie... ...,Romance|Thriller,5.0
6332,"Lizzie McGuire Movie, The (2003)",Children|Comedy|Romance,5.0
6342,"Trip, The (2002)",Comedy|Drama|Romance,5.0
7260,Latter Days (2003),Comedy|Drama|Romance,5.0
8254,Arizona Dream (1993),Comedy|Drama|Fantasy|Romance,5.0
9010,Love Me If You Dare (Jeux d'enfants) (2003),Drama|Romance,5.0
25801,She Done Him Wrong (1933),Comedy|Romance,5.0
26501,Choose Me (1984),Comedy|Romance,5.0
26599,"Law of Desire (Ley del deseo, La) (1987)",Comedy|Drama|Romance,5.0
26791,Shining Through (1992),Drama|Romance|Thriller|War,5.0
26843,Three of Hearts (1993),Comedy|Romance,5.0
27792,"Saddest Music in the World, The (2003)",Comedy|Drama|Fantasy|Musical|Romance,5.0
27826,Touch of Pink (2004),Comedy|Drama|Romance,5.0
31903,Zelary (2003),Drama|Romance,5.0
32525,The Earrings of Madame de... (1953),Drama|Romance,5.0
40226,Wild Zero (2000),Action|Comedy|Horror|Romance|Sci-Fi,5.0
41573,"Family Stone, The (2005)",Comedy|Drama|Romance,5.0
51471,Amazing Grace (2006),Drama|Romance,5.0
59549,Shelter (2007),Drama|Romance,5.0
61013,Absolute Giganten (1999),Action|Comedy|Drama|Romance,5.0
74754,"Room, The (2003)",Comedy|Drama|Romance,5.0
82608,Zerophilia (2005),Comedy|Romance,5.0
86817,Something Borrowed (2011),Comedy|Drama|Romance,5.0
90061,"Myth of the American Sleepover, The (2010)",Comedy|Drama|Romance,5.0
98933,Yossi (Ha-Sippur Shel Yossi) (2012),Drama|Romance,5.0
102753,"Past, The (Le passé) (2013)",Drama|Mystery|Romance,5.0
107412,"Kidnapping, Caucasian Style (Kavkazskaya plenn...",Comedy|Romance,5.0
107555,Fireworks Wednesday (Chaharshanbe-soori) (2006),Drama|Mystery|Romance,5.0
112577,Willie & Phil (1980),Comedy|Drama|Romance,5.0
127052,Operation 'Y' & Other Shurik's Adventures (1965),Comedy|Crime|Romance,5.0
127108,Brooklyn (2015),Drama|Romance,5.0
127728,Back Soon (2007),Drama|Romance,5.0
138696,Hands in the Air (2010),Comedy|Drama|Romance,5.0
140741,Get Your Stuff (2000),Drama|Romance,5.0
140745,10 Attitudes (2001),Comedy|Drama|Romance,5.0
140755,Long-Term Relationship (2006),Comedy|Romance,5.0
140759,The Big Gay Musical (2009),Comedy|Drama|Romance,5.0
140761,The Biggest Fan (2002),Comedy|Romance,5.0
152017,Me Before You (2016),Drama|Romance,5.0
162542,Rustom (2016),Romance|Thriller,5.0

In [24]:
movie_romance_rating_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 301 to 162542
Data columns (total 3 columns):
title     56 non-null object
genres    56 non-null object
rating    56 non-null float64
dtypes: float64(1), object(2)
memory usage: 1.8+ KB